# Generated by Django 4.2.2 on 2024-04-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_cartorder_price_alter_cartorderproducts_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[("KG", "Kilogram"), ("PC", "Piece")],
                default="KG",
                max_length=2,
            ),
        ),
    ]
