# Generated by Django 4.2.2 on 2024-04-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_cartorder_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="cheque_picture",
            field=models.ImageField(blank=True, null=True, upload_to="cheque_pictures"),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
