# Generated by Django 4.2.2 on 2024-04-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_product_old_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="payment_method",
            field=models.CharField(default="COD", max_length=100),
        ),
    ]
