# Generated by Django 4.2.2 on 2024-04-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_cartorder_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorderproducts",
            name="product",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.product",
            ),
        ),
    ]
