# Generated by Django 4.2.2 on 2024-04-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_cartorderproducts_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorderproducts",
            name="product",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
